- hosts: nginx
  vars_files:
  - 'defaults/main.yml'
  tasks:
    - name: Nginx | Install then depedencies
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - build-essential
        - libpcre3
        - libpcre3-dev
        - libssl-dev
        - libgeoip-dev
        - libxslt1-dev
    - include: 'tasks/main.yml'
    - include: 'tasks/compile.yml'
    - name: Nginx | Install the upstart init script
      template:
        src: templates/nginx.init.j2
        dest: /etc/init.d/nginx
        owner: root
        group: root
        mode: 0755
      notify:
        - restart nginx

    - name: Nginx | Register Nginx as a service
      service:
        name: nginx
        enabled: yes