- hosts: nginx
  vars_files:
  - 'defaults/main.yml'
  tasks:
    - name: NGINX|Install then depedencies
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - build-essential
        - libpcre3
        - libpcre3-dev
        - libssl-dev
    - include: 'tasks/main.yml'
    - name: Nginx | Compile the Nginx source
      shell: >
        cd /tmp/{{nginx}}-{{nginx_version}} &&
        ./configure
        --sbin-path=/usr/sbin/nginx 
        --conf-path=/etc/nginx/nginx.conf 
        --pid-path=/var/run/nginx.pid 
        --with-http_ssl_module 
        --with-stream 
        --with-mail=dynamic 
        --with-http_gzip_static_module 
        --add-module=/tmp/ngx_pagespeed-release-{{nginx_pagespeed_version}}-beta &&
        make &&
        make install
    

    - name: Nginx | Install the upstart init script
      template:
        src: templates/nginx.init.j2
        dest: /etc/init.d/nginx
        owner: root
        group: root
        mode: 0755
      notify:
        - restart nginx

    - name: Nginx | Register Nginx as a service
      service:
        name: nginx
        enabled: yes