- name: Nginx | Compile the Nginx source
  shell: >
    cd /tmp/{{nginx}}-{{nginx_version}} &&
    ./configure
    --sbin-path=/usr/sbin/nginx 
    --conf-path=/etc/nginx/nginx.conf 
    --pid-path=/var/run/nginx.pid 
    --error-log-path=/var/log/nginx/error.log 
    --http-log-path=/var/log/nginx/access.log 
    --with-http_gzip_static_module        
    --with-http_stub_status_module        
    --with-http_ssl_module                
    --with-pcre                           
    --with-file-aio   
    --with-mail=dynamic 
    --with-http_gunzip_module
    --with-http_v2_module
    --with-ipv6
    --with-http_realip_module
    --add-module=/tmp/ngx_pagespeed-release-{{nginx_pagespeed_version}}-beta
    --add-module=/tmp/naxsi-{{nginx_naxsi_version}}/naxsi_src &&
    make &&
    make install