- name: Nginx | Create virtual hosts folders
  file: path={{nginx_dir}}/{{item}} state=directory
  with_items:
    - sites-enabled
    - sites-enabled
- name: Nginx | Write the nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf backup=yes